name: Build
run-name: Build for ${{ github.ref_name }} by ${{ github.actor }}
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-hosts:
    timeout-minutes: 60
    name: Build ${{ matrix.host }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - host: axolotl
            runner: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      - name: Set up Cachix
        uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: heitor
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build host
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --accept-flake-config
  build-dev-shells:
    timeout-minutes: 15
    name: Build devShell for ${{ matrix.package }} on ${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        system:
          - aarch64-linux
          - x86_64-linux
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      - name: Set up Cachix
        uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: heitor
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build devShell
        run: nix build .#devShells.${{ matrix.system }}.default --accept-flake-config
  build-formatter:
    timeout-minutes: 14
    name: Build formatter on ${{ matrix.system }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        system:
          - aarch64-linux
          - x86_64-linux
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      - name: Set up Cachix
        uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: heitor
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build formatter
        run: nix build .#formatter.${{ matrix.system }} --accept-flake-config
